# Site settings
title: Nami’s 키워드세상
tagline: 키워드로_바라보는_세상, 기획과 마케팅
description: "사회 현상에 담긴 키워드로 어떤 기획을 할 수 있을까, 기획/마케팅 Thinking+log ."
url: "https://namimov.com"
author:
  name: "Nami"
  email: "hyunjung3445@gmail.com"
  url: "https://namimov.com/"

# Build settings
baseurl: /
markdown: kramdown
permalink: /:title
paginate: 8

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
